export const enum ArticleInfoType {
  type = "y",
  title = "t",
  shortTitle = "s",
  icon = "i",
  author = "a",
  date = "d",
  localizedDate = "l",
  category = "c",
  tag = "g",
  isEncrypted = "n",
  isOriginal = "o",
  readingTime = "r",
  excerpt = "e",
  sticky = "u",
  cover = "v",
  index = "I",
  order = "O",
}
